[package]
name = "sqlite_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
clap_derive = "4.5.47"
indexmap = "2.11.4"
ratatui = "0.29.0"
rusqlite = "0.37.0"
